sudo: required
language: node_js

os:
  - linux
  - linux-ppc64le


cache:
  apt: true
  directories:
    - "$TRAVIS_CACHE_DIR"

branches:
  only:
    - master
    - development
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

services:
  - docker

before_install:
  - make init
  - make cicd-log-init
  - source travis-env.sh
  - make docker-logins
  - chmod +x copyright-check.sh

install:
  - make install

before_script:
  - make test

script:
  - make copyright-check
  - make docker:build

after_success:
  - test "$TRAVIS_EVENT_TYPE" = "pull_request" && make push
  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && make release || echo "success"
  - |
      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != "development"]]; then
        curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
        python travis_after_all.py https://travis.ibm.com/api
        export $(cat .to_export_back)
        if [[ "$BUILD_LEADER" == "YES" ]]; then
          if [[ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ]]; then
            echo "All jobs succeeded! Creating multi arch image..."
            make docker:manifest-tool
            make docker:multi-arch
          else
            echo "Some jobs failed" && exit 1
          fi
        fi
      fi
  - make cicd-log-success

after_failure:
  - make cicd-log-fail

notifications:
  slack:
    on_failure: always
    on_success: change
    on_pull_request: false
    rooms:
      - secure: uJhSvxCfppPv9Ux5r0bgbOVz8u4vxWYhitgpuvBiQt4OGpGUb6GHkzZKl3E1Y27R4NyawULW18csRXfUJQ6hyh1hGjlU5Sh4iztArxqUC1w16VC9vSZaPvseLXulFmv3pcFPFLMJI1iJRBDWNXMvhFjHlXBfK2uD11tbBsf3Kf7L4v1DnU72aDZDPkwRPZiW3TTQpAx9ebdgbdHg+aFhyQPblzo/SHsFyrkALXrpGWI8/XHM+HeLm10SSQ5hMn0ahdwIv97KYo6Z/iVzOy9yoZLTCT7LkXe3lw5WAE+rGpxMy2nXi1vTZp8sJIsbAe/ywhgFor9t7g8qf8fTDptrF+sf5zA173e6RCAYboVG9IuHW0E6Pm5Ip8rBhaQf/JfVYltHsb9yU9kqc1oYGS2e+RpKSIGvx+r6elSNBu+2F3MgtQsSzU3TkuDG90RCxNfEQikDjPNRx7Xc/1AsemMj9/6eETlzODhQDJH/wUfWf7O1r/H7whmPbwm30Od4CO0NowXWoNT8lweSqm+OXYtgySjCj36O30C7ucdZZFHBo3S6zC8KjAIfe1/w9jw/jZ48SP/tvM2QrR0n1MT1gvV06xykRMoDVLZdDwHT3vKQZ5eJzhvn6c8gS2JHZRM6xPOpkzLrsLMpKQiyj11B7svyn79cxiUxrvkN67pAWb2uolo=
    template:
      - "Search API"
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} %{result} in %{duration}"